#PBS -N csr_elic_km
#PBS -o /ghome/gaocs/FCM-NQ/err_out/csr_elic_km.out
#PBS -e /ghome/gaocs/FCM-NQ/err_out/csr_elic_km.err
#PBS -l nodes=1:gpus=1:A,walltime=350:00:00
#PBS -r y
cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes and gpus:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

# -s "/ghome/gaocs/FCM-NQ/job/compressai.sh csr elic2022-official 0.004 400 400 1e-4 48 64-1024 kmeans 10 8 None" \
# -s "/ghome/gaocs/FCM-NQ/job/compressai.sh seg elic2022-official 0.00015 550 550 1e-4 64 256-256 kmeans 10 8  \
#        /gdata1/gaocs/Data_FCM_NQ/dinov2/seg/elic/training_models/trunl-506.97_trunh105.95_kmeans10_bitdepth8/elic2022-official_lambda0.00015_epochs600_lr0.0001_bs64_patch256-256_checkpoint_best.pth.tar" \

# -s "/ghome/gaocs/FCM-NQ/job/compressai.sh csr elic2022-official 0.00015 600 50 1e-4 100 64-1024 kmeans 10 8  \
#        /gdata1/gaocs/Data_FCM_NQ/llama3/csr/elic/training_models/trunl-71.5_trunh47.75_kmeans10_bitdepth8/elic2022-official_lambda0.0001_epochs400_lr0.0001_bs100_patch64-1024_checkpoint_best.pth.tar" \
# -s "/ghome/gaocs/FCM-NQ/job/compressai.sh tti elic2022-official 0.008 600 50 1e-4 12 512-512 kmeans 10 8  \
#        /gdata1/gaocs/Data_FCM_NQ/sd3/tti/elic/training_models/trunl-5.79_trunh4.46_kmeans10_bitdepth8/elic2022-official_lambda0.01_epochs600_lr0.0001_bs12_patch512-512_checkpoint_best.pth.tar" \

startdocker -u " -v /gdata/gaocs:/gdata/gaocs  -v /gdata1/gaocs:/gdata1/gaocs -v /gdata2/gaocs:/gdata2/gaocs --shm-size=16g " \
    -P /ghome/gaocs \
    -s "/ghome/gaocs/FCM-NQ/job/compressai.sh csr elic2022-official 0.008 600 50 1e-4 28 64-4096 kmeans 10 8 None" \
    bit:5000/gaocs_compressai_llama3_container:2.1.1-cuda12.1-cudnn8-runtime

